### ISSUE TITLE
Highlight sidebar border 请把边界提亮

### ISSUE THREAD

**Issue by Yensan** [t7yang/dark-lavender#1]
这主题很好看，好喜欢的冷色调。
在使用的过程中，对比于`深色+(默认深色)`，dark-lavender 的边界不清晰。
比如，打开活动栏，活动栏和编辑区颜色混在一起，如果要鼠标拖动调整分区大小，会很困难
![WeChatbffd68a515bfe1ef67cf16174bdc8ff9](https://user-images.githubusercontent.com/16527206/173847233-fa5e32ce-0841-443e-8be2-225db3dd5cdb.png)

所以，请让边界明显一些。我不会写前端...

**Comment by t7yang** [comment]
確實在辨識是上有點障礙，但我日常使用上並不會到有很大的困擾。
主要是我不是很想用邊界上色的方式解決，也不喜歡側邊欄跟編輯區的背景色不一樣。
但我會再花時間去思考有沒有什麼方式來緩解這個問題，可能不會這麼快。
感謝你提出的建議。

**Comment by Yensan** [comment]
哦。你说的好。我和你想的一样。
上面的图是“区域要划分清楚”的意思，不代表要实现一根突兀的线。`深色+(默认深色)
vscode.theme-defaults` 的边界方案就很不错，它的区域划分很清晰，整体感又很强。
Lavender，很美的主题

**Comment by t7yang** [comment]
沒有什麼比較好的辦法，最後還是選擇用第二背景色當作側邊欄跟編輯區的邊界。
最少應該是可以辨識邊界，有想法的話可以再提出來。

**Comment by Yensan** [comment]
感觉更漂亮了！点击了，被激活的输入窗口，有了主题色，很契合主题。
有个加强边界的办法，就是`深色+(默认深色) vscode.theme-defaults` 那样，不同区块有略微的明度差异，但都是暗色，整体感很强。不过，区块之间明度差异太大的话，就很割裂了。——不同的区块之间呈现差异，自然就有边界了，他们用的设计语言是面。
你现在的更新，是激活的输入窗口提亮解决的。用的设计语言是点和线。
你的这个点和线的解决方案，很灵动。如果加上面，功能性就完美了。但已经有点和线设计语言划分空间了，面与面的区别可以做的比他们的更小一些：整个软件的窗口整体性更强，才能突出点和线的灵动。

**Comment by t7yang** [comment]
主要是我自己不喜歡背景色有差異，當然設計是很主觀的，如果太過遷就使用者也會導致失去設計者本身的初衷。
有些部分也是因為 VSCode 沒有開放足夠多的選項讓我們發揮，所以部分設計如果不能滿足也只能請見諒。
無論如何，非常感謝你喜歡我的設計。
