### ISSUE TITLE
使用主題有發生打字 "字體模糊" 的狀況

### ISSUE THREAD

**Issue by oatsian** [t7yang/dark-lavender#2]
### 問題截圖
![image](https://user-images.githubusercontent.com/103582829/200364266-71951f28-d62c-4552-a33a-ed0b4fde4841.png)

### 問題說明

主題已使用有數個月最近換 mac 後，才發現此狀況經測試確定，我只有再輸入 git commit 資訊時有模糊現象

### 設定
```json
{
  "editor.fontFamily": "Rec Mono Linear",
  "editor.fontLigatures": true,
  "editor.formatOnSave": false,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.wordWrap": "on",
  "editor.tabSize": 2,
  "editor.bracketPairColorization.enabled": true,
  "editor.renderWhitespace": "all",
  "editor.snippetSuggestions": "top",
  "editor.suggest.showWords": false,
  "editor.quickSuggestions": {
    "strings": true
  },
  "editor.codeActionsOnSave": [
    "source.organizeImports",
    "source.formatDocument",
    "source.fixAll.eslint"
  ],
  "cSpell.userWords": ["clsx"],
  "terminal.integrated.fontSize": 14,
  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
  "javascript.updateImportsOnFileMove.enabled": "always",
  "files.autoSave": "onFocusChange",
  "files.eol": "\n",
  "files.associations": {
    "*.css": "tailwindcss"
  },
  "prettier.jsxSingleQuote": true,
  "prettier.singleQuote": true,
  "prettier.trailingComma": "all",
  "prettier.endOfLine": "auto",
  "prettier.printWidth": 60,
  "tailwindCSS.includeLanguages": {
    "plaintext": "html"
  },
  "tailwindCSS.emmetCompletions": true,
  "tailwindCSS.classAttributes": [
    "class",
    "className",
    "ngClass",
    "classes"
  ],
  "tailwindCSS.experimental.classRegex": [
    ":\\s*?[\"'`]([^\"'`]*).*?,",
    ["clsx\\(([^)]*)\\)", "(?:'|\"|`)([^']*)(?:'|\"|`)"]
  ],
  "window.zoomLevel": 1,
  "workbench.fontAliasing": "auto",
  "workbench.colorTheme": "Dark Lavender (Soft)"
}

```

### vscode 版本資訊

版本: 1.73.0 (Universal)
提交: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
日期: 2022-11-01T15:38:50.881Z
電子: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
作業系統: Darwin arm64 21.6.0
Sandboxed: No

**Comment by t7yang** [comment]
看起來應該不太像跟主題有關。
你可以嘗試換用其他主題一段時間測試嗎？
我覺得是 mac 上面的問題，但我自己沒有 mac 設備可以測試。
我這裡也會問問看其他用 mac 的朋友有沒有這個情況，再請你在你的環境換用其他主題一段時間觀察看看。

編輯：
我測試過在 Windows 也會，而且確實只有我的主題會。
但是我目前完全沒有頭緒，因為主題套件不能修改什麼設定，就是套用顏色而已。
要花點時間研究跟測試。

**Comment by caffbit** [comment]
好的, 我做的測試動作如下

- [x] 已關閉所有 extension
- [x] 已關閉所有 setting 還原預設
- [x] 以 “One Dark Pro” and "Dark Lavender" 兩個主題切換測試, 只有 Dark Lavender “中文模糊” “英文不會”

詢問前已去過 vscode github 找過有關字體模糊 issus 找過以下解法

1. https://blog.csdn.net/weixin_44378370/article/details/106843338  (window)
2. https://blog.csdn.net/wejack/article/details/124105758 (mac)

上述經測試結果沒用.

**Comment by t7yang** [comment]
而且是只有在 git 的輸入框才會，其他還不會，目前怎麼想都跟主題無關，不知道 VSCode 在搞什麼鬼。

**Comment by t7yang** [comment]
我有時間會再測試看看不同的顏色是否有印象，主題能夠做的東西真的不多。
然後也已經在 vscode 那裏回報問題，看看他們是否有頭緒
https://github.com/microsoft/vscode/issues/166135

**Comment by caffbit** [comment]
vscode 找到問題處惹，設定嘗試他回覆問題重現的方式。

```json
  "workbench.colorCustomizations": {
    "editor.background": "#0000005c"
  }
```

模糊就出現了🤪 真是神奇... 看來就等vscode 出現更新版就能解決.

**Comment by t7yang** [comment]
真的是神奇的 bug ，但跟我預測的一樣，這問題應該不是主題造成的，畢竟我們只能提供顏色給 VSCode 。
我再來看看是不是有用到透明度

**Comment by caffbit** [comment]
https://github.com/microsoft/vscode/issues/165682#issuecomment-1327884188

>The root cause is that the sizing of inner editor dom nodes needs to be left to the editor, using editor options and the JS API. We shouldn't force certain sizes for private editor dom nodes using CSS.
截取 vscode 團隊一段話，並看到 git commit 有提到

```css
.scm-view .scm-input .margin {
	width: 6px !important;
}

.scm-input .monaco-scrollable-element {
	left: 6px !important;
}
```
推測應該有兩個 DOM 一個 input , 一個 view，非英文的輸入法且需要選字的關係，都造成偏移測試如下

```json
 "workbench.colorCustomizations": {
    "[Dark Lavender]": {
      "input.background": "#3c3c3c",
      "input.foreground": "#181818"
    }
  }
```

![截圖 2022-11-26 下午4 02 59](https://user-images.githubusercontent.com/103582829/204078955-f59db19c-4567-441f-a419-7281feb5bf8a.png)

![截圖 2022-11-26 下午4 09 01](https://user-images.githubusercontent.com/103582829/204079021-4f377890-3df8-4f19-91de-c6891e8da43d.png)

第二張圖使用 Kimbie Dark 主題再去玩一次輸入 “測試” 兩個字，它用帶顏色的遮罩蓋掉白色的文字 (殘影)

結論我找不到輸入時遮罩的那個顏色 (就是 Kimbie Dark 的反黃)

**Comment by t7yang** [comment]
看看他們怎麼修

**Comment by caffbit** [comment]
![截圖 2022-12-22 下午7 21 37](https://user-images.githubusercontent.com/103582829/209123918-33841175-ee1c-4e88-9bcb-b88537d0e56f.png)

vscode 更新以下版本後已正常
版本: 1.74.2 (Universal)
提交: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
日期: 2022-12-20T10:26:09.430Z
電子: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
作業系統: Darwin arm64 21.6.0
Sandboxed: No

**Comment by t7yang** [comment]
@callumzhong 感謝回報，有什麼問題或是建議歡迎再來回饋。
